version: "3"
services:
  prod:
    build: .
    environment:
      - HOST=0.0.0.0
      - DATABASE_URL
      - SESSION_SECRET
      - APP_URL
    ports:
      - 3000:3000
      - 5555:5555
volumes:
  node_modules:
